[error] sbt.librarymanagement.ResolveException: Error downloading org.apache.kafka:kafka_2.11:3.0.0
[error]   Not found
[error]   Not found
[error]   not found: C:\Users\guptas76\.ivy2\localorg.apache.kafka\kafka_2.11\3.0.0\ivys\ivy.xml
[error]   not found: C:\Users\guptas76\.m2\repository\org\apache\kafka\kafka_2.11\3.0.0\kafka_2.11-3.0.0.pom
[error]   not found: https://artifactory.internal.cba/maven-central/org/apache/kafka/kafka_2.11/3.0.0/kafka_2.11-3.0.0.pom
[error]   not found: https://artifactory.internal.cba/analyticsinformation-omnia-ivy/org/apache/kafka/kafka_2.11/3.0.0/kafka_2.11-3.0.0.pom
[error]   Variables not found: scalaVersion, sbtVersion
[error]   not found: https://artifactory.internal.cba/omnia-releases/org/apache/kafka/kafka_2.11/3.0.0/kafka_2.11-3.0.0.pom
[error]   not found: https://artifactory.internal.cba/omnia-dependencies/org/apache/kafka/kafka_2.11/3.0.0/kafka_2.11-3.0.0.pom
[error]   unauthorized: https://artifactory.internal.cba/applicationinfrastructure-cspr-maven/org/apache/kafka/kafka_2.11/3.0.0/kafka_2.11-3.0.0.pom (Artifactory Realm)
[error]   not found: https://artifactory.internal.cba/cloudera/org/apache/kafka/kafka_2.11/3.0.0/kafka_2.11-3.0.0.pom
[error]   not found: https://artifactory.internal.cba/scalasbt/org.apache.kafka/kafka_2.11/3.0.0/ivys/ivy.xml
[error]   not found: https://artifactory.internal.cba/io.jfrog.scala/artifactory/ivy-releases/org.apache.kafka/kafka_2.11/3.0.0/ivys/ivy.xml
[error]   unauthorized: https://artifactory.internal.cba/gist-maven/org/apache/kafka/kafka_2.11/3.0.0/kafka_2.11-3.0.0.pom (Artifactory Realm)
[error] 	at lmcoursier.CoursierDependencyResolution.unresolvedWarningOrThrow(CoursierDependencyResolution.scala:258)
[error] 	at lmcoursier.CoursierDependencyResolution.$anonfun$update$38(CoursierDependencyResolution.scala:227)
[error] 	at scala.util.Either$LeftProjection.map(Either.scala:573)
[error] 	at lmcoursier.CoursierDependencyResolution.update(CoursierDependencyResolution.scala:227)
[error] 	at sbt.librarymanagement.DependencyResolution.update(DependencyResolution.scala:60)
[error] 	at sbt.internal.LibraryManagement$.resolve$1(LibraryManagement.scala:53)
[error] 	at sbt.internal.LibraryManagement$.$anonfun$cachedUpdate$12(LibraryManagement.scala:103)
[error] 	at sbt.util.Tracked$.$anonfun$lastOutput$1(Tracked.scala:73)
[error] 	at sbt.internal.LibraryManagement$.$anonfun$cachedUpdate$20(LibraryManagement.scala:116)
[error] 	at scala.util.control.Exception$Catch.apply(Exception.scala:228)
[error] 	at sbt.internal.LibraryManagement$.$anonfun$cachedUpdate$11(LibraryManagement.scala:116)
[error] 	at sbt.internal.LibraryManagement$.$anonfun$cachedUpdate$11$adapted(LibraryManagement.scala:97)
[error] 	at sbt.util.Tracked$.$anonfun$inputChangedW$1(Tracked.scala:219)
[error] 	at sbt.internal.LibraryManagement$.cachedUpdate(LibraryManagement.scala:130)
[error] 	at sbt.Classpaths$.$anonfun$updateTask0$5(Defaults.scala:3486)
[error] 	at scala.Function1.$anonfun$compose$1(Function1.scala:49)
[error] 	at sbt.internal.util.$tilde$greater.$anonfun$$u2219$1(TypeFunctions.scala:62)
[error] 	at sbt.std.Transform$$anon$4.work(Transform.scala:68)
[error] 	at sbt.Execute.$anonfun$submit$2(Execute.scala:282)
[error] 	at sbt.internal.util.ErrorHandling$.wideConvert(ErrorHandling.scala:23)
[error] 	at sbt.Execute.work(Execute.scala:291)
[error] 	at sbt.Execute.$anonfun$submit$1(Execute.scala:282)
[error] 	at sbt.ConcurrentRestrictions$$anon$4.$anonfun$submitValid$1(ConcurrentRestrictions.scala:265)
[error] 	at sbt.CompletionService$$anon$2.call(CompletionService.scala:64)
[error] 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
[error] 	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
[error] 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
[error] 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
[error] 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
[error] 	at java.lang.Thread.run(Thread.java:750)
[error] (flinkApp / ssExtractDependencies) sbt.librarymanagement.ResolveException: Error downloading org.apache.kafka:kafka_2.11:3.0.0
[error]   Not found
[error]   Not found
[error]   not found: C:\Users\guptas76\.ivy2\localorg.apache.kafka\kafka_2.11\3.0.0\ivys\ivy.xml
[error]   not found: C:\Users\guptas76\.m2\repository\org\apache\kafka\kafka_2.11\3.0.0\kafka_2.11-3.0.0.pom
[error]   not found: https://artifactory.internal.cba/maven-central/org/apache/kafka/kafka_2.11/3.0.0/kafka_2.11-3.0.0.pom
[error]   not found: https://artifactory.internal.cba/analyticsinformation-omnia-ivy/org/apache/kafka/kafka_2.11/3.0.0/kafka_2.11-3.0.0.pom
[error]   Variables not found: scalaVersion, sbtVersion
[error]   not found: https://artifactory.internal.cba/omnia-releases/org/apache/kafka/kafka_2.11/3.0.0/kafka_2.11-3.0.0.pom
[error]   not found: https://artifactory.internal.cba/omnia-dependencies/org/apache/kafka/kafka_2.11/3.0.0/kafka_2.11-3.0.0.pom
[error]   unauthorized: https://artifactory.internal.cba/applicationinfrastructure-cspr-maven/org/apache/kafka/kafka_2.11/3.0.0/kafka_2.11-3.0.0.pom (Artifactory Realm)
[error]   not found: https://artifactory.internal.cba/cloudera/org/apache/kafka/kafka_2.11/3.0.0/kafka_2.11-3.0.0.pom
[error]   not found: https://artifactory.internal.cba/scalasbt/org.apache.kafka/kafka_2.11/3.0.0/ivys/ivy.xml
[error]   not found: https://artifactory.internal.cba/io.jfrog.scala/artifactory/ivy-releases/org.apache.kafka/kafka_2.11/3.0.0/ivys/ivy.xml
[error]   unauthorized: https://artifactory.internal.cba/gist-maven/org/apache/kafka/kafka_2.11/3.0.0/kafka_2.11-3.0.0.pom (Artifactory Realm)
